version: "3"
jobs:
  build:
    docker:
      - image: golang:1.8

    working_directory: /go/src/github.com/mlabouardy/moviedb

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: go get -v

      - run:
          name: Unit Tests
          command: go test -v
